### ISSUE TITLE
prot. Nter mod. not parsed for Alphapept

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#508]
**Describe the bug**
The variable modifications on N-ter of proteins is not parsed in AlphaPept. It is not in the parameters listed in the datapoint. 

For now, we should at least write it down in the documentation so that this is clear to all. 

it looks like this in the parameter file (acetylation):
```
mods_variable_terminal_prot:
  - a<^
```

I will merge the current data point and put here the hash it corresponds to. This way parameter file will be available.

**Comment by mlocardpaulet** [comment]
Here is the link to the data: https://proteobench.cubimed.rub.de/datasets/1bfa914c771321b285a9ca40d4aa538cb9fdc42e/

**Comment by mlocardpaulet** [comment]
this one too has modifications on the protein N-ter, but this is not parsed correctly in the current version:
```
mods_variable_terminal_prot:
  - a<^
```

**Comment by mlocardpaulet** [comment]
I think that we should combine all modifications mentioned in the paramter file:
```
fasta:
  AL_swap: false
  KR_swap: false
  fasta_block: 1000
  fasta_size_max: 100
  isoforms_max: 1024
  mods_fixed:
  - cC
  mods_fixed_terminal: []
  mods_fixed_terminal_prot: []
  mods_variable:
  - oxM
  mods_variable_terminal: []
  mods_variable_terminal_prot:
  - a<^
  n_missed_cleavages: 2
  n_modifications_max: 3
  pep_length_max: 27
  pep_length_min: 7
  protease: trypsin
  pseudo_reverse: true
  save_db: true
  spectra_block: 100000
```

What do you think?
